[Package] Separate single-shot and pipeline API.
nnstreamer/api pull request #131
Opened 2022-01-24 05:51 UTC by gichan-jang

- `machine-learning-inference` is separated to `machine-learning-inference-single` and `machine-learning-inference-pipeline`.
 - Move `ml_validate_model_file` to `ml-api-inference-single.c`

Signed-off-by: Gichan Jang <gichan2.jang@samsung.com>

2022-02-12 06:02 UTC, myungjoo commented
```
[   69s] /home/abuild/rpmbuild/BUILD/capi-machine-learning-inference-1.8.0/c/src/ml-api-inference-internal.c:16:10: fatal error: nnstreamer_plugin_api_util.h: No such file or directory
[   69s]    16 | #include <nnstreamer_plugin_api_util.h>
[   69s]       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   69s] compilation terminated.
```

2022-02-24 05:55 UTC, myungjoo commented on packaging/machine-learning-api.spec
> +Requires:	capi-machine-learning-inference-sinlge = %{version}-%{release}
TYPO: "sinlge"

2022-02-24 05:56 UTC, myungjoo reviewed
Test the final product with a simple test app using nnstreamer-single-api.rpm in Tizen device (or in gbs). It will fail.

2022-02-28 05:37 UTC, myungjoo requested changes
Backward compatibility is broken.

An app with ```Requires: capi-machine-learning-inference-devel``` will be broken.

Add dependency from devel to single-devel and pipeline-devel so that previous applications can be kept built after this commit.

2022-03-02 05:31 UTC, gichan-jang commented
> Backward compatibility is broken.
> 
> An app with `Requires: capi-machine-learning-inference-devel` will be broken.
> 
> Add dependency from devel to single-devel and pipeline-devel so that previous applications can be kept built after this commit.


https://github.com/gichan-jang/api/blob/1899b0fb2651e11f86f1f2308c1d97e44e881174/packaging/machine-learning-api.spec#L143-L151
I think dependencies has already been made. Please let me know if I missed something.

2022-03-03 07:36 UTC, myungjoo approved these changes
LGTM

2022-03-03 07:37 UTC, myungjoo commented
> > Backward compatibility is broken.
> > An app with `Requires: capi-machine-learning-inference-devel` will be broken.
> > Add dependency from devel to single-devel and pipeline-devel so that previous applications can be kept built after this commit.
> 
> https://github.com/gichan-jang/api/blob/1899b0fb2651e11f86f1f2308c1d97e44e881174/packaging/machine-learning-api.spec#L143-L151 I think dependencies has already been made. Please let me know if I missed something. I built this package using gbs, and built the `nnstreamer-example`, it was passed.

My bad. I missed "devel" package was "capi-machine-learning-inference-devel".

2022-03-03 07:37 UTC, merged

2022-03-10 15:59 UTC, zhoonit commented on c/meson.build
> +ml_inf_conf.set('ML_INFERENCE_REQUIRE', 'capi-nnstreamer-single capi-nnstreamer-pipeline')
ML_INFERENCE_REQUIRE requires those two